# Generated by Django 4.2 on 2023-04-12 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.IntegerField()),
                ('route', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Автомобильные перевозки',
                'verbose_name_plural': 'Автомобильные перевозки',
            },
        ),
        migrations.CreateModel(
            name='Necessary_equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Необходимая техника',
                'verbose_name_plural': 'Необходимая техника',
            },
        ),
        migrations.CreateModel(
            name='Passenger_Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_passengers', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Пассажирские перевозки',
                'verbose_name_plural': 'Пассажирские перевозки',
            },
        ),
        migrations.CreateModel(
            name='Rent_of_special_equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('necessary_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.necessary_equipment')),
            ],
            options={
                'verbose_name': 'Аренда спецтехники',
                'verbose_name_plural': 'Аренда спецтехники',
            },
        ),
    ]
