# Generated by Django 4.2 on 2023-04-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cartransport_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent_of_special_equipment',
            name='necessary_equipment',
        ),
        migrations.AddField(
            model_name='passenger_transportation',
            name='freight_fromto',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent_of_special_equipment',
            name='truck_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
